---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15

inputs:
  - name: dp-reporter-client
    path: dp-reporter-client

run:
  path: dp-reporter-client/ci/scripts/build.sh
